"""Run-level PROV-O provenance for the full-corpus run.

scripts/validation/integration_seam_test.py proves the PER-PARAGRAPH chain
wires up. This script adds the full per-run provenance: ONE graph
binding the committed results artifact (tcfd_scored.csv, by sha256) to exactly
the inputs and instrument version that produced it -

    dataset + 5 pinned model commits + instrument tag rulebase-locked-v1
        --(corpus_run activity)-->  tcfd_scored.csv

so any score in the paper is re-derivable from a single provenance record.

Reads run_manifest.json (single source of truth) + hashes the CSV.
Emits artifacts/provenance/corpus_run.ttl (+ .json).

Run:  uv run python scripts/provenance_corpus_run.py
"""
import hashlib
import json
import pathlib
from datetime import datetime

from prov.model import Namespace, ProvDocument

from greenrisk.metadata import INSTRUMENT_METHOD, INSTRUMENT_RULE_COUNT

ROOT = pathlib.Path(__file__).resolve().parents[1]
RUN_DIR = ROOT / "artifacts" / "corpus_run"
CSV = RUN_DIR / "tcfd_scored.csv"
MANIFEST = RUN_DIR / "run_manifest.json"
OUT_DIR = ROOT / "artifacts" / "provenance"


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def main():
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    csv_hash = sha256_file(CSV)
    expected_hash = manifest["outputs"][CSV.name]["sha256"]
    if csv_hash != expected_hash:
        raise ValueError(
            f"artifact integrity failure for {CSV}: expected {expected_hash}, got {csv_hash}"
        )
    when = datetime.fromisoformat(manifest["timestamp_utc"])

    doc = ProvDocument()
    gr = Namespace("gr", "https://github.com/idcesares/GreenRisk/prov/")
    hf = Namespace("hf", "https://huggingface.co/")
    doc.set_default_namespace("https://github.com/idcesares/GreenRisk/prov/")
    doc.add_namespace(gr)
    doc.add_namespace(hf)

    version = manifest["software_version"]
    agent = doc.agent(
        f"gr:GreenRiskPipeline_v{version}",
        {"prov:type": "prov:SoftwareAgent", "gr:version": version},
    )

    # The locked instrument as a first-class entity (rules + MFs, frozen).
    instrument = doc.entity("gr:instrument_" + manifest["instrument_tag"],
                             {"prov:type": "gr:FuzzyInstrument",
                             "gr:tag": manifest["instrument_tag"],
                             "gr:commit": manifest["instrument_commit"],
                             "gr:n_rules": str(INSTRUMENT_RULE_COUNT),
                             "gr:defuzz": INSTRUMENT_METHOD})

    # The input dataset.
    dataset = doc.entity("gr:dataset_tcfd",
                          {"prov:type": "gr:Corpus",
                           "gr:name": manifest["dataset"],
                          "gr:revision": manifest["dataset_revision"],
                          "gr:sha256": manifest["dataset_train_sha256"],
                          "gr:n_total": str(manifest["n_total"])})

    # The run activity (timestamps from the manifest).
    run = doc.activity("gr:corpus_run", when, when,
                       {"prov:type": "gr:CorpusRun",
                        "gr:gate": str(manifest["gate"]),
                        "gr:n_total": str(manifest["n_total"]),
                        "gr:n_kept": str(manifest["n_kept"]),
                        "gr:batch_size": str(manifest["batch_size"])})
    doc.wasAssociatedWith(run, agent)
    doc.used(run, dataset)
    doc.used(run, instrument)

    # The 5 pinned models, each used by the run.
    for short, commit in manifest["model_revisions"].items():
        repo = manifest["model_repositories"][short]
        e_model = doc.entity("hf:" + repo,
                             {"prov:type": "gr:PretrainedModel",
                              "gr:short_name": short,
                              "gr:commit_hash": commit})
        doc.used(run, e_model)

    # The results artifact, bound by sha256, generated by the run.
    results = doc.entity("gr:tcfd_scored_csv",
                         {"prov:type": "gr:ScoredCorpus",
                          "gr:filename": CSV.name,
                          "gr:n_rows": str(manifest["n_kept"]),
                          "gr:sha256": expected_hash})
    doc.wasGeneratedBy(results, run)
    doc.wasDerivedFrom(results, dataset)
    doc.wasDerivedFrom(results, instrument)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    ttl = OUT_DIR / "corpus_run.ttl"
    js = OUT_DIR / "corpus_run.json"
    doc.serialize(str(ttl), format="rdf", rdf_format="ttl")
    doc.serialize(str(js), format="json")

    print(f"results artifact sha256 = {csv_hash}")
    print(f"wrote {ttl}")
    print(f"wrote {js}")
    print(f"\nrun: used dataset + instrument({manifest['instrument_tag']}) "
          f"+ 5 pinned models -> {CSV.name} ({manifest['n_kept']} rows)")


if __name__ == "__main__":
    main()
