"""Render existing PROV-O provenance artifacts to PNG.

This intentionally reads already-emitted provenance files (.ttl or PROV JSON)
instead of rebuilding provenance from manifests/results. It is useful when the
run source data is gone and only the provenance artifact remains.

Run:
    uv run python scripts/render_provenance_png.py artifacts/provenance/corpus_run.ttl
    uv run python scripts/render_provenance_png.py artifacts/provenance/contrast_run.ttl
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable

import matplotlib.pyplot as plt
import networkx as nx
from matplotlib.lines import Line2D
from prov.model import ProvDocument
from rdflib import Graph, Literal, URIRef
from rdflib.namespace import RDF, PROV


GR = "https://greenrisk.ppgi.ufrj.br/prov/"
HF = "https://huggingface.co/"

RELATIONS = {
    PROV.used: "used",
    PROV.wasGeneratedBy: "generated by",
    PROV.wasDerivedFrom: "derived from",
    PROV.wasAssociatedWith: "associated with",
}


def parse_provenance(path: Path) -> Graph:
    graph = Graph()
    suffix = path.suffix.lower()

    if suffix in {".ttl", ".turtle"}:
        graph.parse(path, format="turtle")
        return graph

    if suffix == ".json":
        doc = ProvDocument.deserialize(str(path), format="json")
        graph.parse(data=doc.serialize(format="rdf", rdf_format="ttl"), format="turtle")
        return graph

    raise ValueError(f"Unsupported provenance format: {path.suffix}")


def _literal_value(graph: Graph, node: URIRef, predicate_suffix: str) -> str | None:
    predicate = URIRef(GR + predicate_suffix)
    for value in graph.objects(node, predicate):
        return str(value)
    return None


def _prov_kind(graph: Graph, node: URIRef) -> str:
    if (node, RDF.type, PROV.Activity) in graph:
        return "activity"
    if (node, RDF.type, PROV.Agent) in graph:
        return "agent"
    return "entity"


def _domain_type(graph: Graph, node: URIRef) -> str | None:
    for value in graph.objects(node, RDF.type):
        if isinstance(value, Literal):
            return str(value).removeprefix("gr:").removeprefix("prov:")
    return None


def _short_id(node: URIRef) -> str:
    text = str(node)
    if text.startswith(GR):
        return text.removeprefix(GR)
    if text.startswith(HF):
        return text.removeprefix(HF).split("/")[-1]
    return text.rsplit("/", 1)[-1].rsplit("#", 1)[-1]


def node_label(graph: Graph, node: URIRef) -> str:
    domain_type = _domain_type(graph, node)
    short_name = _literal_value(graph, node, "short_name")
    filename = _literal_value(graph, node, "filename")
    tag = _literal_value(graph, node, "tag")
    dataset_name = _literal_value(graph, node, "name")

    title = filename or short_name or tag or _short_id(node)
    lines = [title]
    if domain_type:
        lines.append(domain_type)

    for attr in ("n_total", "n_kept", "n", "n_gate_pass", "n_rows", "gate", "n_rules"):
        value = _literal_value(graph, node, attr)
        if value is not None:
            lines.append(f"{attr}: {value}")

    if dataset_name and dataset_name != title:
        lines.append(dataset_name)

    commit = _literal_value(graph, node, "commit_hash")
    if commit:
        lines.append(f"commit: {commit[:10]}")

    digest = _literal_value(graph, node, "sha256")
    if digest:
        lines.append(f"sha256: {digest[:12]}")

    return "\n".join(lines)


def build_display_graph(rdf: Graph) -> nx.DiGraph:
    display = nx.DiGraph()

    for subject, predicate, obj in rdf:
        if predicate not in RELATIONS or not isinstance(subject, URIRef) or not isinstance(obj, URIRef):
            continue
        for node in (subject, obj):
            display.add_node(
                str(node),
                label=node_label(rdf, node),
                kind=_prov_kind(rdf, node),
                domain_type=_domain_type(rdf, node) or "",
                uri=str(node),
            )
        display.add_edge(str(subject), str(obj), label=RELATIONS[predicate])

    return display


def _layer_for_node(data: dict[str, str]) -> int:
    kind = data["kind"]
    domain_type = data["domain_type"]
    uri = data["uri"]

    if kind == "agent":
        return 1
    if kind == "activity":
        return 2
    if "Scored" in domain_type or "Stats" in domain_type:
        return 3
    if "PretrainedModel" in domain_type or "Instrument" in domain_type:
        return 1
    if "dataset" in uri.lower() or "contrast_set" in uri.lower():
        return 0
    return 0


def layout_graph(graph: nx.DiGraph) -> dict[str, tuple[float, float]]:
    layers: dict[int, list[str]] = {}
    for node, data in graph.nodes(data=True):
        layers.setdefault(_layer_for_node(data), []).append(node)

    positions: dict[str, tuple[float, float]] = {}
    for layer, nodes in sorted(layers.items()):
        nodes.sort(key=lambda n: graph.nodes[n]["label"])
        y_step = 2.25
        start = (len(nodes) - 1) * y_step / 2
        for index, node in enumerate(nodes):
            y = 0.0 if len(nodes) == 1 else start - (index * y_step)
            positions[node] = (float(layer) * 3.3, y)

    return positions


def _draw_edges(graph: nx.DiGraph, pos: dict[str, tuple[float, float]], ax: plt.Axes) -> None:
    styles = {
        "used": {"edge_color": "#606060", "style": "solid"},
        "generated by": {"edge_color": "#2d7f46", "style": "solid"},
        "derived from": {"edge_color": "#7656a7", "style": "dashed"},
        "associated with": {"edge_color": "#b36b00", "style": "dotted"},
    }

    for label, style in styles.items():
        edges = [(u, v) for u, v, data in graph.edges(data=True) if data["label"] == label]
        if not edges:
            continue
        nx.draw_networkx_edges(
            graph,
            pos,
            edgelist=edges,
            arrows=True,
            arrowsize=18,
            arrowstyle="-|>",
            connectionstyle="arc3,rad=0.08",
            width=1.5,
            min_source_margin=20,
            min_target_margin=20,
            **style,
        )

    handles = [
        Line2D([0], [0], color=style["edge_color"], linestyle=style["style"], linewidth=2, label=label)
        for label, style in styles.items()
        if any(data["label"] == label for _, _, data in graph.edges(data=True))
    ]
    ax.legend(handles=handles, loc="lower center", ncol=4, frameon=False, fontsize=8)


def render_png(source: Path, output: Path) -> None:
    rdf = parse_provenance(source)
    graph = build_display_graph(rdf)
    if graph.number_of_nodes() == 0:
        raise ValueError(f"No PROV relationships found in {source}")

    pos = layout_graph(graph)
    width = max(12.0, 3.6 * max(1, len({x for x, _ in pos.values()})))
    max_layer_size = max(1, max(sum(1 for _, data in graph.nodes(data=True) if _layer_for_node(data) == layer) for layer in range(4)))
    height = max(7.5, 1.35 * max_layer_size)

    fig, ax = plt.subplots(figsize=(width, height), dpi=180)
    ax.set_title(source.stem.replace("_", " ").title() + " Provenance", fontsize=16, pad=20)
    ax.axis("off")

    colors = {
        "entity": "#fff2a8",
        "activity": "#b9daf6",
        "agent": "#f6c68f",
    }
    shapes = {
        "entity": "o",
        "activity": "s",
        "agent": "p",
    }

    for kind in ("entity", "activity", "agent"):
        nodes = [node for node, data in graph.nodes(data=True) if data["kind"] == kind]
        if not nodes:
            continue
        nx.draw_networkx_nodes(
            graph,
            pos,
            nodelist=nodes,
            node_shape=shapes[kind],
            node_color=colors[kind],
            edgecolors="#333333",
            linewidths=1.1,
            node_size=3800 if kind != "agent" else 3400,
        )

    _draw_edges(graph, pos, ax)
    nx.draw_networkx_labels(
        graph,
        pos,
        labels=nx.get_node_attributes(graph, "label"),
        font_size=7.2,
        font_family="DejaVu Sans",
    )

    # Keep long labels from being clipped by Matplotlib's default margins.
    xs = [point[0] for point in pos.values()]
    ys = [point[1] for point in pos.values()]
    x_pad = max(1.3, (max(xs) - min(xs)) * 0.08)
    y_pad = max(1.0, (max(ys) - min(ys)) * 0.18)
    ax.set_xlim(min(xs) - x_pad, max(xs) + x_pad)
    ax.set_ylim(min(ys) - y_pad, max(ys) + y_pad)

    output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output, bbox_inches="tight", facecolor="white")
    plt.close(fig)


def default_output_path(source: Path) -> Path:
    return source.with_suffix(".png")


def iter_sources(paths: Iterable[str]) -> Iterable[Path]:
    for value in paths:
        yield Path(value)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("sources", nargs="+", help="PROV-O .ttl or PROV JSON files to render")
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=None,
        help="Optional output directory. Defaults to next to each source file.",
    )
    args = parser.parse_args()

    for source in iter_sources(args.sources):
        output = (args.out_dir / source.with_suffix(".png").name) if args.out_dir else default_output_path(source)
        render_png(source, output)
        print(f"wrote {output}")


if __name__ == "__main__":
    main()
