# ===========================================================================
# GreenRisk W1 Finalization — Part 2: First PROV-O Graph
# ===========================================================================
#
# CONCEPT: WHAT IS PROV-O AND WHY DO WE CARE?
#
#   PROV-O is a W3C standard for tracking provenance — the history of how a
#   piece of data came to exist. Think of it as a directed graph where:
#
#     - ENTITIES are things that exist (a paragraph, a model, a score)
#     - ACTIVITIES are things that happened (tokenization, inference, scoring)
#     - AGENTS are who/what caused things to happen (ClimateBERT, the pipeline)
#
#   Connected by a small vocabulary of relationships:
#     - wasGeneratedBy: "this score was generated by this inference activity"
#     - used: "this activity used this paragraph as input"
#     - wasAssociatedWith: "this activity was done by this agent"
#     - wasDerivedFrom: "this output derives from this input"
#
#   For our pipeline, PROV-O gives us an auditable chain from:
#     input paragraph → preprocessing → model inference → fuzzy aggregation → risk score
#
#   Every node has metadata (timestamps, model commit hashes, parameter values).
#   The graph is exported as Turtle (.ttl), a standard RDF serialization format
#   that your professors and any FAIR-data reviewer will recognize immediately.
#
# WHY NOW (IN W1)?
#   Two reasons:
#     1. If provenance tracking is an afterthought bolted on in W5, it'll be
#        incomplete and fragile. By emitting the first graph in W1, we prove
#        the infrastructure works before we depend on it.
#     2. This is the dissertation hook. The PROV-O graph is the artifact that
#        makes this work citable beyond the course — it's what the ISN
#        Verification Oracle will use to publish attestation provenance chains.
#
# HOW TO RUN:
#   First: uv add prov   (if not already installed)
#   Then:  uv run python w1_first_provenance.py
#
# OUTPUT:
#   - first_provenance.ttl  (the PROV-O graph in Turtle format)
#   - first_provenance.png  (a visualization, if graphviz is installed)
#   - Console printout of the graph for inspection
# ===========================================================================

import json
import hashlib
import os
import shutil
from datetime import datetime
from datetime import timezone
from pathlib import Path

# The `prov` library implements the W3C PROV data model in Python.
# It can create PROV documents, serialize them to various formats
# (Turtle, JSON, PROVN), and optionally visualize them.
from prov.model import ProvDocument, Namespace, PROV_TYPE
from prov.dot import prov_to_dot  # optional: requires pydot + graphviz


def _graphviz_install_hint() -> str:
    if shutil.which("winget"):
        return "Install Graphviz binary (Windows): winget install Graphviz.Graphviz"
    return "Install Graphviz and ensure the 'dot' executable is on PATH."


def _ensure_dot_on_path() -> bool:
    if shutil.which("dot"):
        return True

    windows_candidates = (
        Path("C:/Program Files/Graphviz/bin"),
        Path("C:/Program Files (x86)/Graphviz/bin"),
    )
    for candidate in windows_candidates:
        dot_exe = candidate / "dot.exe"
        if dot_exe.exists():
            os.environ["PATH"] = f"{candidate}{os.pathsep}{os.environ.get('PATH', '')}"
            return shutil.which("dot") is not None

    return False


def build_first_provenance(
    paragraph_text: str,
    model_name: str,
    model_commit_hash: str,
    output_label: str,
    output_probability: float,
) -> ProvDocument:
    """
    Build a minimal PROV-O document tracing one paragraph through one model.

    This is the simplest possible provenance graph. In W2+ we'll extend it
    to cover all five models and the fuzzy inference layer. But the structure
    is the same — we're just adding more nodes and edges.
    """

    doc = ProvDocument()

    # === NAMESPACES ===
    # Namespaces are just URL prefixes that make the graph readable.
    # "gr:" is our project namespace; "hf:" points to HuggingFace.
    gr = Namespace("gr", "https://greenrisk.ppgi.ufrj.br/prov/")
    hf = Namespace("hf", "https://huggingface.co/")
    # prov expects a URI string here, not a Namespace object
    doc.set_default_namespace("https://greenrisk.ppgi.ufrj.br/prov/")
    doc.add_namespace(gr)
    doc.add_namespace(hf)

    # === ENTITIES ===
    # Things that exist. Each gets a unique identifier and metadata.

    # The input paragraph
    para_hash = hashlib.sha256(paragraph_text.encode()).hexdigest()[:12]
    e_paragraph = doc.entity(
        f"gr:paragraph_{para_hash}",
        {
            "prov:type": "gr:InputParagraph",
            "gr:text_preview": paragraph_text[:100] + "...",
            "gr:text_sha256": para_hash,
            "gr:char_count": len(paragraph_text),
        },
    )

    # The model (as an entity — it's a thing that exists on the Hub)
    e_model = doc.entity(
        f"hf:{model_name}",
        {
            "prov:type": "gr:PretrainedModel",
            "gr:huggingface_repo": model_name,
            "gr:commit_hash": model_commit_hash,
        },
    )

    # The output score
    e_score = doc.entity(
        f"gr:score_{para_hash}_{model_name.split('/')[-1]}",
        {
            "prov:type": "gr:ClassificationScore",
            "gr:label": output_label,
            "gr:probability": str(output_probability),
            "gr:model_used": model_name,
        },
    )

    # === ACTIVITIES ===
    # Things that happened. In this minimal graph, there's one: inference.

    a_inference = doc.activity(
        f"gr:inference_{para_hash}_{model_name.split('/')[-1]}",
        datetime.now(timezone.utc),  # start time
        datetime.now(timezone.utc),  # end time (same for quick inference)
        {
            "prov:type": "gr:ModelInference",
            "gr:model_repo": model_name,
            "gr:model_commit": model_commit_hash,
            "gr:truncation": "True",
            "gr:max_length": "512",
        },
    )

    # === AGENTS ===
    # Who/what caused things to happen.

    ag_pipeline = doc.agent(
        "gr:GreenRiskPipeline_v0.1",
        {
            "prov:type": "prov:SoftwareAgent",
            "gr:version": "0.1.0",
        },
    )

    # === RELATIONSHIPS ===
    # This is where the graph becomes a graph.

    # The score was generated by the inference activity
    doc.wasGeneratedBy(e_score, a_inference)

    # The inference activity used the paragraph and the model
    doc.used(a_inference, e_paragraph)
    doc.used(a_inference, e_model)

    # The inference activity was associated with the pipeline agent
    doc.wasAssociatedWith(a_inference, ag_pipeline)

    # The score derives from the paragraph (shortcut relation)
    doc.wasDerivedFrom(e_score, e_paragraph)

    return doc


if __name__ == "__main__":
    # === CONFIGURATION ===
    # Replace these with your actual values from models.py
    TEST_PARAGRAPH = (
        "We are committed to achieving net-zero greenhouse gas emissions across "
        "our entire value chain by 2050. Our sustainability strategy places "
        "climate action at the core of our business, creating long-term value "
        "for shareholders while contributing to a more sustainable future."
    )
    MODEL_NAME = "climatebert/distilroberta-base-climate-detector"
    MODEL_HASH = "PASTE_YOUR_HASH_HERE"  # from your pin_models.py output

    # Simulated output (replace with actual inference result when you run it)
    OUTPUT_LABEL = "yes"
    OUTPUT_PROB = 0.997

    # === BUILD THE GRAPH ===
    print("Building PROV-O document...")
    doc = build_first_provenance(
        paragraph_text=TEST_PARAGRAPH,
        model_name=MODEL_NAME,
        model_commit_hash=MODEL_HASH,
        output_label=OUTPUT_LABEL,
        output_probability=OUTPUT_PROB,
    )

    # === SERIALIZE TO TURTLE ===
    output_dir = Path(__file__).resolve().parents[1] / "artifacts" / "provenance"
    output_dir.mkdir(parents=True, exist_ok=True)
    ttl_path = output_dir / "first_provenance.ttl"
    doc.serialize(str(ttl_path), format="rdf", rdf_format="ttl")
    print(f"\nTurtle file written: {ttl_path}")

    # Print the Turtle content so you can see what a PROV-O graph looks like
    print("\n" + "=" * 70)
    print("PROV-O GRAPH (Turtle format)")
    print("=" * 70)
    with open(ttl_path, encoding="utf-8") as f:
        print(f.read())

    # === OPTIONAL: VISUALIZE ===
    try:
        if not _ensure_dot_on_path():
            raise RuntimeError(_graphviz_install_hint())

        dot = prov_to_dot(doc)
        png_path = output_dir / "first_provenance.png"
        dot.write_png(str(png_path))
        print(f"Visualization written: {png_path}")
        print("(Open it to see the graph visually — entities are yellow ovals,")
        print(" activities are blue rectangles, agents are orange pentagons.)")
    except Exception as e:
        print(f"\nVisualization skipped: {e}")
        if "graphviz" not in str(e).lower() and "dot" not in str(e).lower():
            print(_graphviz_install_hint())
        print("Not required — the .ttl file is the actual deliverable.")

    # === SERIALIZE TO JSON (alternative format) ===
    json_path = output_dir / "first_provenance.json"
    doc.serialize(str(json_path), format="json")
    print(f"\nJSON file written: {json_path}")

    print("\n" + "=" * 70)
    print("W1 CHECKPOINT: FIRST PROV-O GRAPH EMITTED")
    print("=" * 70)
    print("""
    What you now have:
      1. A .ttl file containing a valid W3C PROV-O graph.
      2. It traces: input paragraph → inference activity → output score.
      3. The model is identified by repo name AND commit hash.
      4. The paragraph is identified by a SHA-256 content hash.

    What this grows into in W2-W3:
      - Four more model-inference branches (one per scoring dimension).
      - A fuzzy-inference node that consumes the four scores.
      - The final risk score + rule activation trace as output entities.
      - Per-run metadata: timestamp, environment hash, random seed.

    The structure does not change. We just add more nodes and edges to
    the same graph. That's why building it now matters — the pattern
    is established, and extending it is mechanical.

    COMMIT THIS:
      git add first_provenance.ttl first_provenance.json
      git add w1_finalize_models.py w1_first_provenance.py
      git commit -m "W1 complete: all models verified, first PROV-O graph emitted"
    """)